### ISSUE TITLE
Import/Export SVG path string

### ISSUE THREAD

**Issue by paulo-raca** [colinmeinke/points#15]
I found the methods in this library very useful, but it lacks a way to import/export shapes from/to anything else. SVG path strings seem like a good intermediary representation.

I wrote this small method for exporting to an SVG path, maybe it can be integrated into the library?

```
function svgPath(shape) {
  ret = [];
  
  for (let i = 0, l = shape.length; i < l; i++) {
    elem = shape[i];
    if (elem.moveTo) {
      ret.push("M", elem.x, elem.y);
    } else if (elem.curve && elem.curve.type == 'arc') {
      ret.push("A", elem.curve.rx, elem.curve.ry, elem.curve.xAxisRotation || 0, elem.curve.largeArcFlag || 0, elem.curve.sweepFlag || 0, elem.x, elem.y);
    } else if (elem.curve && elem.curve.type == 'cubic') {
      ret.push("C", elem.curve.x1, elem.curve.y1, elem.curve.x2, elem.curve.y2, elem.x, elem.y);
    } else if (elem.curve && elem.curve.type == 'quadratic') {
      ret.push("Q", elem.curve.x1, elem.curve.y1, elem.x, elem.y);
    } else {
      ret.push("L", elem.x, elem.y);
    }
  }
  return ret.join(" ");
}
```

For importing, maybe we could use https://github.com/hughsk/svg-path-parser

**Comment by derhuerst** [comment]
I'd vote for keeping format-specific exporters & importers out of this lib, to keep its footprint small. What about creating a `points-to-svg` package?

**Comment by paulo-raca** [comment]
That works too

**Comment by colinmeinke** [comment]
Thanks for the request, it's a good idea, that's why I've already made this over at [svg-points](https://github.com/colinmeinke/svg-points) 😄 

It converts points to and from an svg object. The `toPath` function converts a set of points to a path d string. There's currently no function to turn a target dom node into an svg object, but it's worth thinking about (I'll open an issue for discussion).

I'll also definitely add a note to the points readme to point people towards svg-points. 

Good to know other people are finding this useful!

**Comment by paulo-raca** [comment]
Awesome, thanks!
